### ISSUE TITLE
Typo / Excessively passive phrasing 

### ISSUE THREAD

**Issue by jaysonmc** [sara-sabr/ITResearch-Prototyping#6]
•Moving the organization towards potientially examining BYOD

1. Typo 'potientially' -> potentially 
2. Would recommend less passive wording ... that's two cushion words in one sentence. Doesn't inspire confidence. Perhaps something a tad more confident, such as ... 

"Organization will explore BYOD opportunities to realize inefficiencies"

Even that `realize efficiencies` seems like fluff to me ... any who, for your consideration. 

(I try to apply these rules to everything I write. We have the book if you`d like to read it) ...
Bad Strategy 
https://medium.com/mbreads/good-strategy-bad-strategy-b37b2563a4a3

Fluff — is a form of gibberish masquarading as strategic concepts or arguments.

Failure to face the challenge — when you cannot define the challenge you cannot evaluate a strategy and improve it

Mistaking goals for strategy — often they are just statements of desire than plans for overcoming obstacles

Bad strategic objectives — when they fail to address critical issues or when they are impracticable

**Comment by e-wu** [comment]
Fixed
